# Generated by Django 5.0 on 2024-01-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='info',
            name='message',
            field=models.TextField(default='how are you'),
        ),
        migrations.AddField(
            model_name='info',
            name='name',
            field=models.TextField(default='name'),
        ),
        migrations.AddField(
            model_name='info',
            name='subject',
            field=models.CharField(default='nepal', max_length=255),
        ),
    ]
